### ISSUE TITLE
Throughput of quic-go

### ISSUE THREAD

**Issue by alexj0l** [quic-go/quic-go#3670]
Hi community,

I am testing the maximum achievable throughput of quic-go and for this purpose I've modified the `echo.go` example to read a large file (>15GB) and send it to a server. The client and server are running on two different hosts (Ubuntu 22) with a unused 10Gigabit link between them. I am achieving a maximum throughput of ca. 1100 Mbit/s. Would be this number expect by anyone else or should quic-go actually be able to achieve more? I'm open to feedback to improve my example so that we can see a better throughput.
Thanks in advance.

**Comment by kokes** [comment]
I haven't looked at the echo code, but you might be limited by this single payload scenario. In a more request-heavy scenario I've been able to push 10-15 Gbits from a single host quite easily (even with some added complexity, not just copying bytes back and forth) and I believe I've seen people do even more (check past issues here).

**Comment by alexj0l** [comment]
@kokes Thank you for your reply, would you share with me your example where you were able to push that big amount of Gbit per second? Sounds very interesting to me and would be very handful proof of quic-go for my thesis. Thanks in advance.

**Comment by kokes** [comment]
It's a pretty complex codebase, so I can't quite extract the logic into a minimal example. But simply open up multiple streams and push (smaller) payloads through them. You should see much higher aggregate tput then.

Looking at the echo example - you'll need to dispatch the handlers in the server part (right now it sequentially processes the first stream on one connection at a time), that should be just a goroutine with some coordination. And same on the client side - launch multiple requests through new bidirectional streams.

**Comment by alexj0l** [comment]
Okay, thank you for information. I'll try it out.

**Comment by alexj0l** [comment]
I'm not a big expert in Go, could you give me a hint how many streams should I open?

**Comment by alexj0l** [comment]
I tried with multiple streams(up to 32) by sending smaller files (200MB and 2GB) and I get almost always a throughput around 1100Mbit/s.

**Comment by marten-seemann** [comment]
We're currently not using batched writes, so it's not unexpected that you can't fill a 10 Gbit link.

There's been work on using the `sendmmsg` API in https://github.com/lucas-clemente/quic-go/pull/3524, which surfaced that we were allocating like crazy, which was killing performance due to GC constantly kicking in. In the mean time, we've done a lot of work to reduce allocs, and we'll be done >80% once we merge all the outstanding PRs linked in https://github.com/lucas-clemente/quic-go/issues/3526.
There's also some subtle issues with how Go delivers packets from the kernel to the QUIC layer, which affect how timely we can acknowledge incoming packets, which has complicated implications on the congestion controller.

Other than that, there's a new Go API in the works to allow batched writes in a more efficient way: https://github.com/lucas-clemente/quic-go/issues/3563. I expect huge performance improvements from this, but obviously we'll have to wait for this API to actually be implemented before we can put numbers on this.

**Comment by Lemonn** [comment]
Just a hint. Running into a bottleneck due to encryption is a real concern at 10G. You need to make sure, that you can encrypt traffic at a rate of at least 10G.

We performed similar tests in a 10G network years ago, probably even on the same Network. If I could remember correctly, we archived thru-puts of around 350 Mbit/s. We linked the limit to a bottleneck in the encryption/decryption of the network traffic. Enabling AES-NI in Bios resulted in a real improvement. After enabling it, we archived thru-puts similar to yours.

**Comment by baryluk** [comment]
This is quite important.

Single stream HTTP/1.1 with TLS 1.2/1.3 (AESGCM128 afaik), can do about 360MB/s (3600Mbps) on a single core (no ktls). C (openssl, wget, curl), Go (`net/http`), Python (`requests`) all show me about 350MB/s one way over single stream (Python about 220MB/s). I was not able to reach 25Gbps, not even close.

In theory QUIC maybe could do even better by exploiting more CPU parallelism. But very fat streams are a bit niche. Still, QUIC should not regress compared to HTTP/1.1 with TLS 1.3.

AMD Threadripper 2950X, Zen+, 3.2GHz. So a bit dated.

**Comment by marten-seemann** [comment]
quic-go now enables GSO by default. This should bring down CPU load quite a bit, and improve throughput on connections that were previously CPU-limited.
