### ISSUE TITLE
http/3 much slower than http/1.1

### ISSUE THREAD

**Issue by SyngoPredevelopment** [quic-go/quic-go#3729]
Doing a comparison between http/1.1 and http/2 and http/3.
For http/3.0 i am using quic-go.

The code for reading/writing files is the same in all cases,
in both cases if i send the files in an async mode (n go worker) or sync mode (single routine) 
the performance is much worse with http/3 than for example with http/1.1.

For http/1.1 i get almost 100% usage of 10Gbit network traffic, for http/3.0 only 40% of network usage.
The CPU is also not the limiting factor, in both cases it uses only < 10% CPU.

I am using go 1.20.2.
Server part for http/3 is (using UDP):

```
var quicConf *quic.Config = nil
server := http3.Server{
	Handler:    handler,
	Addr:       bCap,
	QuicConfig: quicConf,
}
err = server.ListenAndServeTLS(certFile, keyFile)
```

Client part:
```
var quicConf *quic.Config = nil
roundTripper := &http3.RoundTripper{
		TLSClientConfig: &tls.Config{
			RootCAs:            pool,
			InsecureSkipVerify: *insecure,
		},
		QuicConfig: quicConf,
}
defer roundTripper.Close()

hclient := &http.Client{
		Transport: roundTripper,
}
...
r, err := http.NewRequest(http.MethodPost, url, bytes.NewBuffer(fileContents))
```

Do I miss some special settings which would increase the performance ?

**Comment by marten-seemann** [comment]
Comparing with HTTP/1.1 is unfair, since that's unencrypted. At the very least, you'd need to compare to HTTPS.

There's a bunch of issues here commenting on performance, for example https://github.com/quic-go/quic-go/issues/3670. You can find a lot more when you search through the issues.

https://github.com/quic-go/quic-go/issues/3563 is one of the main reasons we can't achieve super high data rates at the moment.

**Comment by SyngoPredevelopment** [comment]
Sorry, but i use TLS 1.3 also for HTTP/1.1, that means it's comparable. So it's HTTPS/1.1 vs. HTTPS/3.
I will watch the issue 3563 and will check again.

**Comment by zllovesuki** [comment]
@SyngoPredevelopment Do note that UDP does not benefit from the many optimizations that the kernel provides, see https://blog.cloudflare.com/how-to-receive-a-million-packets/

Currently quic-go does not use the batch API, which will limit performance. The patch to add that is WIP by @marten-seemann

**Comment by SyngoPredevelopment** [comment]
Did a test again with latest 0.37.0, still same behavior, performance http3 with quic-go and http3 vs http1.1 (both with TLS1.3) is still quite different. http3 is only getting to 30% compared to http1.1.  My project is under https://github.com/SyngoPredevelopment/HTTPx, i can share it if somebody would check the issue with quic-go.

**Comment by baryluk** [comment]
Have you loooked into using `sendmmsg` and `recvmmsg` on Linux. It allows to send/receive multiple messages on a single socket. I am pretty sure it works for UDP too. They also work in nonblocking if desiered, and for receive one can do blocking for >=1 messages, but if no more is in buffers, return immediately (or with timeout).

They could be useful to reduce syscall overheads substantially probably. In TCP usually one does not need that because one can pass very big buffer to write/send/sendmsg, and it will be split by kernel into proper TCP segments, and be taken care of. One cannot do the same for UDP with normal write/send/sendmsg.
