### ISSUE TITLE
can not access http3

### ISSUE THREAD

**Issue by Inasayang** [quic-go/quic-go#3890]
```go
package main

import (
    "github.com/quic-go/quic-go/http3"
    "log"
    "net/http"
)

func main() {
    mux := http.NewServeMux()
    mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
        w.Write([]byte("Hello, HTTP/3!"))
    })
    log.Fatal(http3.ListenAndServeQUIC("0.0.0.0:8443", "/usr/local/pki/cert.pem", "/usr/local/pki/cert-key.pem", mux))
}
```
![image](https://github.com/quic-go/quic-go/assets/30060632/3a84847e-8a9c-42c5-8632-389d37816a5d)

- no firewall
- Chrome has enabled quic

But can't access.

**Comment by aitay721822** [comment]
Use `http3.ListenAndServe` instead of `http3.ListenAndServeQUIC`.
Because ListenAndServeQUIC only listens to udp networks, in the http/3 protocol the client first needs to discover if an HTTP/3 server exists on the endpoint before opening a QUIC connection.

The "ALT-SVC" http header or HTTP/2 ALTSVC frame is required to discover the http/3 server.

For more information.
https://www.rfc-editor.org/rfc/rfc9114.html#name-discovering-an-http-3-endpo

**Comment by marten-seemann** [comment]
HTTP/3 support works. We won’t be able to help you debug your setup.
