### ISSUE TITLE
how to access connection error

### ISSUE THREAD

**Issue by fholzer** [quic-go/quic-go#3958]
I am using quic directly, not http3. While working on my app I found that there's no way to easily access the error cause when a connection is closed. The only way to get the error is to call `conn.AcceptStream()`, though some use cases may not need one side of the connection to accept streams. That side would be unable to access the error reason (application error, transport error, etc) to learn why its connection might get closed. I might have missed something, maybe you can give me some pointers?

After some digging I thought it would be great to get these errors as cancel cause on the connection context, which works fine for me. Any thoughts? Only downside I came up with is that cancel causes were introduced in go1.20
My changes: https://github.com/fholzer/quic-go/compare/master...fholzer:quic-go:surface-conn-err

While I am writing this, I realize that it might be nice to do the same for stream errors on stream contexts.

**Comment by marten-seemann** [comment]
> The only way to get the error is to call `conn.AcceptStream()`, though some use cases may not need one side of the connection to accept streams

That's correct, or `OpenStream`, or any read / write operation on the stream. This is equivalent to how a `net.TCPConn` works, you also only get the error when you do something with the connection.

That said, I like your solution :) We already have the context, and since Go 1.20 we can attach an error. I don't see any reason to not do it. Could you send us a PR? We might be able to include it in the v0.37 release, which will probably be released some time next week.

For the stream errors, could you send a separate PR?
