### ISSUE TITLE
OpenStreamSync  non-blocking

### ISSUE THREAD

**Issue by lemoidului** [quic-go/quic-go#4107]
Hello,  
I may have misunderstood the proper use of the library, but OpenStreamSync() does not wait for the peer (AcceptStream call) to respond before continuing in a non-blocking manner.   
You can check this by using the example/echo/echo.go code snippet, just adding a delay before AcceptStream.  
Is this normal behavior?  
- go version: 1-21-1 linux amd64
- quic-go v0.39.0  

Thanks for your work.

**Comment by Glonee** [comment]
`OpenStreamSync` will wait only if the peer is reaching its stream limit until a new stream can be opened, while `OpenStream` will return an error instead of blocking.
Unlike TCP, in QUIC connections, the peer can only accept the stream after data has been sent on the stream, which means if you just call `OpenStream` without sending data on the stream, the peer won't know about anything of the stream(The `AcceptStream` call will keep blocking).

**Comment by marten-seemann** [comment]
@Glonee is right. The documentation says "It blocks until a new stream can be opened.". Nowhere does this say or even imply that it waits until the peer has called `AcceptStream`.

**Comment by lemoidului** [comment]
Okay, I get it. Thanks for the clarification
