### ISSUE TITLE
Clarify the usage of StatelessResetToken

### ISSUE THREAD

**Issue by zllovesuki** [quic-go/quic-go#4395]
For someone like me who RTFM but still can't understand if:

1. StatelessResetToken needs to be the same for all servers?
2. StatelessResetToken should be unique per server?
3. StatelessResetToken should be the same for clients and servers?

Assuming that the servers are load balanced via anycast and routed based on ConnectionID (hence no migration is considered).

Could we clarify how the token should be used?

**Comment by marten-seemann** [comment]
Hi @zllovesuki, that's a very good question!

> StatelessResetToken should be the same for clients and servers?

No, and there's no way to communicate the token between clients and servers.

> Assuming that the servers are load balanced via anycast and routed based on ConnectionID (hence no migration is considered).

With anycast, the routing can change at any moment. Packets intended for one server would then end up at a different server, which doesn't have access to the TLS session keys. In that case, you'd want the client to learn about this as quickly as possible (otherwise the client has to wait for the idle timeout). With a stateless reset, the client's connection would be closed right away.

So to answer your question, all servers participating in the anycast setup should share the same stateless reset key.


---
I've actually been working on a new documentation site for quic-go, since some QUIC concepts need a little bit more context than one can reasonably provide within the godoc framework. I'm not quite ready to launch yet, but expect some news in the next week(s).

What I can share at this point is the section about stateless resets. What do you think? Would that have been helpful to answer your question?

<img width="702" alt="image" src="https://github.com/quic-go/quic-go/assets/1478487/9c94f5a7-53b4-4859-860a-a3a8bf9120f7">

**Comment by zllovesuki** [comment]
That's sufficient information! Thank you for clarifying

**Comment by marten-seemann** [comment]
Great, thanks for confirming! I'm really looking forward to launching the new docs website :)

I'm going to close this issue for now. Feel free to reopen if you have any more questions about stateless resets.
